- hosts: all
  gather_facts: true
  become: true
  vars:
    swap_file_size_mb: "{{ [(ansible_memory_mb.real.total / 2), 65536] | min | int }}"
  #   ansible_user: root
  tasks:
    - name: Update all packages
      ansible.builtin.package:
        name: "*"
        state: latest
        update_cache: true
      notify:
        - Reboot vm
    - name: Install base packages
      ansible.builtin.package:
        name:
          - mc
          - htop
          - iotop
          - net-tools
          - atop
          - htop
          - unzip
          - netperf
          - python3-pip
  roles:
    - swap
  handlers:
    - name: Reboot vm
      ansible.builtin.reboot:
