- hosts: all
  gather_facts: true
  vars:
    ansible_user: root
    sysctl_param_state: present # absent
  tasks:
    - name: Set vm.swappiness
      ansible.posix.sysctl:
        name: vm.swappiness
        value: 5
        state: "{{ sysctl_param_state }}"
      notify:
        - Reboot vm
    
    # $ head -1 /var/lib/postgresql/postmaster.pid
    # 7192
    # grep ^VmPeak /proc/$(head -1 /var/lib/postgresql/15/main/postmaster.pid)/status
    # VmPeak:	 2238736 kB
    # grep ^Hugepagesize /proc/meminfo
    # Hugepagesize:       2048 kB
    # round (2238736 / 2048) = 
    - name: Set vm.nr_hugepages
      ansible.posix.sysctl:
        name: vm.nr_hugepages
        value: 1094
        state: "{{ sysctl_param_state }}"
      notify:
        - Reboot vm
    - name: Set vm.overcommit_memory
      ansible.posix.sysctl:
        name: vm.overcommit_memory
        value: 2
        state: "{{ sysctl_param_state }}"
      notify:
        - Reboot vm
    - name: Set vm.overcommit_ratio
      ansible.posix.sysctl:
        name: vm.overcommit_ratio
        value: 50
        state: "{{ sysctl_param_state }}"
      notify:
        - Reboot vm
    - name: Disable transparent_hugepage
      ansible.builtin.shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled

  handlers:
    - name: Reboot vm
      ansible.builtin.reboot:
